---
title: "Dollar-RealYields"
author: "Ben Buzzee"
date: "March 26, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(vars)
library(xts)
require(quantmod)


gold <- read.csv("gold.csv", na.strings = ".")
names(gold) <- c("date", "price")
gold$date <- as.Date(gold$date, format = "%Y-%m-%d")
gold <- xts(gold$price, order.by = gold$date)

getSymbols("GDX")
gdxRets <- CalculateReturns(Cl(GDX))


getFedData <- function(tag = "DFF"){
  
  #=== pull data ===#
  api.key <- "59f051c54cc49a42ef1f3ba3426792b8"
  fred <- FredR::FredR(api.key)
  
  # REQUIRES global fred object to be loaded
  dt <- fred$series.observations(tag)
  dt <- dt %>% as.tibble()
  
  print("removing NAs")
  # remove NA's
  dt$value <- as.numeric(dt$value)
  dt <- dt[!is.na(dt$value),]
  
  #=== clean dataframe up ===#
  print("cleaning data")
  # remove unneeded columns
  dt <-  dt %>% dplyr::select(date, value) %>% dplyr::mutate(date = as.Date(date))
  
  # round all dates to nearest month
  #dt$date <- dt$date %>% lubridate::round_date(unit = "month")
  
  # for each month only retain median value
  #dt <- dt %>% dplyr::group_by(date) %>% dplyr::summarize(value = median(value))
  
  return(dt)
  
}


yields <- getFedData(tag = "DFII10")
yields <- xts(yields$value, order.by = yields$date)


df <- merge(yields, gold, join = "inner")
```


```{r}
plot(log(gold), grid.ticks.on = "years")

plot(Cl(GDX))

```
```{r}

sma <- SMA(df$yields, n = 22*12)

plot(yields, grid.ticks.on = "years")
lines(sma)


goldRets <- CalculateReturns(gold)
plot(goldRets)
signal <- yields < sma


rets <- lag(signal, 2) * goldRets

stratStats(tail(rets, 252*10))
```

```{r}
ccf(x = df$dollar, y = df$gold_price, lag.max = 100)
```








```{r}
VARselect(df[,-1])

var_fit <- VAR(df[,-1], p = 2)

plot(var_fit$varresult$dollar$residuals)


summary(var_fit$varresult$gold_price)

fitted <- xts(fitted(var_fit$varresult$gold_price), order.by = df$date[-c(1,2)])

plot.xts(df_ts$gold[-c(1,2)], grid.ticks.on = "years", type = "o")
points(fitted, col = "red")



```

```{r}
plot(predict(var_fit, n.ahead = 5))
```

